name: CI CD

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ""
      LATEST_TAG: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            nasih1204/cmskit:latest

  deploy:
    name: Apps Deployment
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to Server
        run: |
          curl -u ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_PASSWORD }} http://103.178.153.216:8080/job/aspnetcore-job/build?token=TOKEN_APPS
